#!/usr/bin/env bun
/**
 * PreToolUse (Edit | Write | MultiEdit | NotebookEdit): blocks hand edits to generated files.
 *
 * Design tokens are generated from `packages/tokens/src` by `bun run tokens`; lockfiles are
 * owned by bun / cargo. Editing the output directly would be overwritten (and fails CI's
 * `tokens:check`), so Claude is told where the source of truth lives instead.
 */

import { allow, block, editedFile, readHookInput, type ToolHookInput } from './hook.shared';

interface GuardRule {
  readonly test: (path: string) => boolean;
  readonly reason: string;
}

const TOKENS_REASON = [
  'This file is GENERATED by the design-token pipeline and must not be edited by hand.',
  'Edit the typed source in packages/tokens/src (tokens/*.tokens.ts, themes/*.theme.ts),',
  'then run `bun run tokens` to regenerate CSS, the Tailwind theme, TS, JSON and the Rust crate.',
].join(' ');

const rules: readonly GuardRule[] = [
  {
    test: (p) => p.startsWith('packages/tokens/src/generated/'),
    reason: TOKENS_REASON,
  },
  {
    test: (p) => p.startsWith('crates/design-tokens/src/generated/'),
    reason: TOKENS_REASON,
  },
  {
    test: (p) => /^packages\/design-system\/src\/icons\/[^/]+\.generated\.ts$/.test(p),
    reason:
      'This icon map is GENERATED by packages/design-system/scripts. Change the script input and re-run it instead.',
  },
  {
    test: (p) => /^desktop\/[^/]+\/src-tauri\/gen\//.test(p),
    reason:
      'src-tauri/gen is generated by the Tauri CLI. Change tauri.conf.json or capabilities/ instead.',
  },
  {
    test: (p) => p === 'bun.lock' || p === 'Cargo.lock',
    reason:
      'Lockfiles are written by `bun install` / cargo. Change package.json (catalog) or Cargo.toml and let the tool update the lockfile.',
  },
];

const input = await readHookInput<ToolHookInput>();
const path = editedFile(input);

if (path !== undefined) {
  const hit = rules.find((rule) => rule.test(path));
  if (hit !== undefined) {
    block(`Blocked edit to ${path}: ${hit.reason}`);
  }
}

allow();
