/**
 * Canonical token key sets. Adding a key here forces every theme to define it
 * (see `ThemeDefinition` in token.types.ts) and every emitter to output it.
 */

export const NORD_COLOR_KEYS = [
  'nord-0',
  'nord-1',
  'nord-2',
  'nord-3',
  'nord-4',
  'nord-5',
  'nord-6',
  'nord-7',
  'nord-8',
  'nord-9',
  'nord-10',
  'nord-11',
  'nord-12',
  'nord-13',
  'nord-14',
  'nord-15',
] as const;

/**
 * Derived shades. Naming: `nord-{n}-{l|d}{ΔL×100}` = OKLCH lightness shift,
 * `nord-{a}-m{b}-{pct}` = pct% of a mixed over b, plus named specials.
 */
export const DERIVED_COLOR_KEYS = [
  'nord-0-d03',
  'nord-3-bright',
  'nord-3-bright-d05',
  'nord-4-m0-85',
  'nord-4-m0-75',
  'nord-4-m0-35',
  'nord-3-m6-45',
  'snow-bright',
  'nord-8-l03',
  'nord-8-d04',
  'nord-9-l04',
  'nord-9-l08',
  'nord-9-d14',
  'nord-9-d20',
  'nord-10-d08',
  'nord-10-d10',
  'nord-10-d12',
  'nord-11-l16',
  'nord-11-d08',
  'nord-11-d10',
  'nord-13-l03',
  'nord-13-d08',
  'nord-13-d20',
  'nord-13-d36',
  'nord-14-l03',
  'nord-14-d08',
  'nord-14-d12',
  'nord-14-d28',
] as const;

/** T1 semantic colour roles → `--gs-color-{key}` → Tailwind `bg-{key}`, `text-{key}`, … */
export const SEMANTIC_COLOR_KEYS = [
  // Surfaces
  'canvas',
  'surface',
  'surface-sidebar',
  'surface-panel',
  'surface-raised',
  'surface-popover',
  'surface-dialog',
  'surface-sunken',
  'field',
  'scrim',
  // Borders
  'border-subtle',
  'border',
  'border-strong',
  // Text
  'fg-strong',
  'fg',
  'fg-secondary',
  'fg-muted',
  'fg-disabled',
  'on-accent',
  // Accent
  'accent',
  'accent-hover',
  'accent-active',
  'accent-fg',
  'accent-subtle',
  'accent-border',
  // Focus & selection
  'focus',
  'focus-halo',
  'selection',
  'selection-inactive',
  // Fills & controls
  'fill-hover',
  'fill-pressed',
  'fill-selected-inactive',
  'control',
  'control-hover',
  'control-pressed',
  'track',
  'thumb',
  // Status: solid · solid hover · text on solid · text on surfaces · subtle bg · border
  'danger',
  'danger-hover',
  'on-danger',
  'danger-fg',
  'danger-subtle',
  'danger-border',
  'warning',
  'warning-hover',
  'on-warning',
  'warning-fg',
  'warning-subtle',
  'warning-border',
  'success',
  'success-hover',
  'on-success',
  'success-fg',
  'success-subtle',
  'success-border',
  'info',
  'info-hover',
  'on-info',
  'info-fg',
  'info-subtle',
  'info-border',
] as const;

/** T2 window-chrome roles → `--gs-{key}` → Tailwind `bg-{key}`, `text-{key}`, … */
export const CHROME_COLOR_KEYS = [
  'titlebar-bg',
  'titlebar-bg-inactive',
  'titlebar-fg',
  'titlebar-fg-inactive',
  'titlebar-border',
  'command-center-bg',
  'command-center-bg-hover',
  'command-center-border',
  'statusbar-bg',
  'statusbar-fg',
  'statusbar-bg-hover',
  'statusbar-bg-active',
  'statusbar-accent-bg',
  'statusbar-accent-fg',
  'statusbar-accent-bg-hover',
  'statusbar-border',
  'tab-strip-bg',
  'tab-active-bg',
  'tab-indicator',
  'tooltip-bg',
  'tooltip-fg',
  'tooltip-border',
  'traffic-close',
  'traffic-minimize',
  'traffic-maximize',
  'traffic-close-pressed',
  'traffic-minimize-pressed',
  'traffic-maximize-pressed',
  'traffic-inactive',
  'traffic-rim',
  'traffic-glyph',
  'scrollbar-thumb',
  'scrollbar-thumb-hover',
  'scrollbar-thumb-active',
] as const;

/** Elevation: control(1) · card(2) · popover(3) · dialog(4) · inset (fields). */
export const SHADOW_KEYS = ['control', 'card', 'popover', 'dialog', 'inset'] as const;
