import { describe, expect, test } from 'bun:test';

import {
  checkBranch,
  checkCommit,
  checkIdentity,
  checkText,
  parseIdent,
  parseLog,
} from '../lib/attribution';

const OWNER = { name: 'ATOMANGELETTI', email: 'DUSTIN@ANGELETTI.SPACE' };

describe('checkText', () => {
  test('passes a normal message and plain tooling mentions', () => {
    expect(checkText('m', 'feat(launcher): add a tray menu\n\nBody.')).toEqual([]);
    expect(checkText('m', 'chore(agents): update .claude/rules and CLAUDE.md')).toEqual([]);
  });

  test('rejects agent trailers, session links and footers', () => {
    const reasons = (text: string) => checkText('m', text).map(({ reason }) => reason);
    expect(reasons('fix: x\n\nCo-Authored-By: Claude Opus <noreply@anthropic.com>')).toHaveLength(
      1,
    );
    expect(reasons('fix: x\n\nco-authored-by: Someone <bot@anthropic.com>')).toHaveLength(1);
    expect(reasons('fix: x\n\nClaude-Session: https://example.com/s')).toHaveLength(1);
    expect(reasons('Body\n\nhttps://claude.ai/code/session_01abc')).toHaveLength(1);
    expect(reasons('🤖 Generated with [Claude Code](https://claude.com/claude-code)')).toHaveLength(
      1,
    );
    expect(reasons('_Generated by [Claude Code](https://claude.ai/code)_')).toHaveLength(2);
  });

  test('keeps a human co-author', () => {
    expect(checkText('m', 'fix: x\n\nCo-Authored-By: Jo <jo@example.com>')).toEqual([]);
  });
});

describe('checkIdentity', () => {
  test('passes the owner and rejects an agent name or anthropic.com email', () => {
    expect(checkIdentity('c', 'author', OWNER.name, OWNER.email)).toEqual([]);
    expect(checkIdentity('c', 'author', 'Claude', 'noreply@anthropic.com')).toHaveLength(1);
    expect(checkIdentity('c', 'committer', 'Bot', 'bot@anthropic.com')).toHaveLength(1);
  });
});

describe('checkBranch', () => {
  test('rejects branch names that name the agent', () => {
    expect(checkBranch('feat/tray-menu')).toEqual([]);
    expect(checkBranch('claude/kind-brahmagupta-j4bg82')).toHaveLength(1);
  });
});

describe('parseLog + checkCommit', () => {
  test('reads git log records and flags only the agent commit', () => {
    const record = (fields: readonly string[]) => `${fields.join('\u001F')}\u001E\n`;
    const output =
      record(['a'.repeat(40), OWNER.name, OWNER.email, OWNER.name, OWNER.email, 'feat: a\n']) +
      record([
        'b'.repeat(40),
        'Claude',
        'noreply@anthropic.com',
        'Claude',
        'noreply@anthropic.com',
        'feat: b\n\nClaude-Session: https://claude.ai/code/session_x\n',
      ]);
    const [owner, agent, ...rest] = parseLog(output);
    expect(rest).toEqual([]);
    expect(owner && checkCommit(owner)).toEqual([]);
    // Author, committer, session trailer and session link.
    expect(agent && checkCommit(agent)).toHaveLength(4);
  });
});

describe('parseIdent', () => {
  test('splits git var output', () => {
    expect(parseIdent('ATOMANGELETTI <DUSTIN@ANGELETTI.SPACE> 1700000000 +0000')).toEqual(OWNER);
  });
});
